### ISSUE TITLE
Error with latest version of docker file when linking a deal.II executable

### ISSUE THREAD

**Issue by blaisb** [dealii/docker-files#35]
Dear all, 
There seems to be an issue with the latest version of the docker image for deal.II master.
Whenever it links an executable, the following error is thrown:
```
/usr/local/lib/libdeal_II.so.10.0.0-pre: error: undefined reference to 'setupterm'
/usr/local/lib/libdeal_II.so.10.0.0-pre: error: undefined reference to 'tigetnum'
/usr/local/lib/libdeal_II.so.10.0.0-pre: error: undefined reference to 'set_curterm'
/usr/local/lib/libdeal_II.so.10.0.0-pre: error: undefined reference to 'del_curterm'
```
This just appeared out of the blue in the last 2-3 days, so something recent with the image must have brought this. Any clues?
Thanks :)!

**Comment by jppelteret** [comment]
Seems related:
- https://stackoverflow.com/a/21477408
- https://linux.die.net/man/3/tigetnum

It seems that some dependency doesn't link against `-ltinfo` or `-lcurses`, so we might have to do this ourselves?

**Comment by peterrum** [comment]
This affects all out projects as well (CC @mschreter, @nfehn, @kronbichler, @slfuchs).

**Comment by luca-heltai** [comment]
I have been using the latest docker image, with no issues. :|  This seems very strange to me. 

Are you using clang to compile, or gcc?

**Comment by luca-heltai** [comment]
Ok I could reproduce this with the latest merge. I reverted the dependencies to use symengine without llvm support (for the moment). @jppelteret, do you know how to workaround this? #34 is the issue. We might need to add some additional compile flags to fix the issues.

**Comment by jppelteret** [comment]
@luca-heltai I've never encountered this issue, so other than the extra linker flags `-ltinfo` or `-lcurses` I don't have any further suggestions. LLVM pops up frequently in a search for `error: undefined reference to 'setupterm'`, but since `ncurses` is transitively included by spack, and I then get spack to set up my environment, I think that I've avoided any potential issues here. Can you simply export those extra linker flags in Docker, or add them to the SymEngine build?

**Comment by luca-heltai** [comment]
Adding LDFLAGS="-ltinfo -lcurse" to the env fixed this. I'm trying the option of adding the to symengine now, and recompiling master image with the new version. If this works, I'll open a PR.

**Comment by luca-heltai** [comment]
A little more investigation produced the following result:

- building symengine with shared libs instead of static libs seems to have fixed the issue (no linking with `tinfo` and `curses` seems to be required by the shared version of the libraries)
- I've just re-built the dependencies and the latest master, and pushed them to dockerhub. Could you check that these images work for you? @blaisb, @peterrum? If they do, I'll merge

**Comment by bangerth** [comment]
The most significant semantic difference between static and shared libs is that a static library is really just something like a tar file of the different `.o` files. It does not store any semantic information such as other libraries it depends on, and so it is not a mistake that the static lib doesn't say that you need to link against `tinfo` and `curses`: There is simply no way to say that. You have to remember that and specify it on the command line by hand whenever you link with that static library.

Shared libraries, on the other hand, can carry this kind of information and if they don't, then that's a bug.

**Comment by peterrum** [comment]
> If they do, I'll merge

I'll report tomorrow the results of the nightly tests.

**Comment by peterrum** [comment]
Looks good :+1:
